#!/bin/bash

# This program outputs the system information page

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
	cat <<- _EOF_
	<h2>System Uptime</h2>
	<pre>$(uptime)</pre>
	_EOF_
	return
}

report_disk_space () {
	cat <<- _EOF_
	<h2>Disk Space Utilization</h2>
	<pre>$(df -h)</pre>
	_EOF_
	return
}

report_home_space () {
	if [[ "$(id -u)" -eq 0 ]]; then #Check if user is a Superuser
		cat <<- _EOF_
		<h2>Home Space Utilization (All Users)</h2>
		<pre>$(du -sh /home/*)</pre>
		_EOF_
	else
		cat <<- _EOF_
		<h2>Home Space Utilization ($USER)</h2>
		<pre>$(du -sh $HOME)</pre>
		_EOF_
	fi
	return
}



cat << _EOF_

<html>
	<head>
       		<title> $TITLE </title>
	</head>

	<body> 
		<h1> $TITLE </h1> 
		$TIMESTAMP
		$(report_uptime)	
		$(report_disk_space)	
		$(report_home_space)	
	</body>
</html>
_EOF_
